version: "3.7"

services:
  frontend:
    build: ./frontend
    command: npm run dev 
    ports:
      - "3000:3000"
  #backend:
  #  build: ./backend
  #  command: mvn spring-boot:run
  #  networks:
  #    - backend-db
  #  ports:
  #    - "8080:8080"
  db:
    image: mysql:8.0
    networks:
      - backend-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pelikan
      - MYSQL_DATABASE=pelikan
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
networks:
  backend-db:
    driver: bridge